services:
  mongo:
    image: mongo
    container_name: annoncenet-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  laravel:
    build:
      context: .
    container_name: annoncenet-back
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data: